# Generated by Django 2.2.6 on 2020-05-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='author',
        ),
        migrations.RemoveField(
            model_name='test',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='test',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='test',
            name='language',
        ),
        migrations.RemoveField(
            model_name='test',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
    ]
