# Generated by Django 2.2.6 on 2020-05-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200527_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
